pipeline:
  build:
    image: rust
    commands:
      - cargo build
  lint:
    image: rust
    commands:
      - rustup component add rustfmt clippy
      - cargo fmt -- --check --files-with-diff
      - cargo clippy --no-deps
